name: Check PR
on:
  workflow_dispatch:
  pull_request:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - run: |
          wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
          chmod +x /usr/local/bin/hadolint
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-python@v4.5.0
      - uses: cloudposse/github-action-pre-commit@v3.0.0
